apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xoz8l6ymb-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xoz8l6ymb-java-springboot-gitops